sudo: false

language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 5.5
      env: dependencies=lowest

before_script:
  - composer install --no-interaction -o
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest; fi;

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
